### ISSUE TITLE
Error of generating XML

### ISSUE THREAD

**Issue by nskw** [robotology/simmechanics-to-urdf#11]
I tried to generate XML files using SimMechanics Link in Creo. 
But I got the attached message. 
Does anyone know possible reasons?

![error_message](https://cloud.githubusercontent.com/assets/15374963/10817770/87b00ce0-7e7f-11e5-96d3-fb87438c8ab9.png)

**Comment by traversaro** [comment]
I never saw this error. 
Perhaps posting the full error log could be helpful. 

cc @fiorisi

**Comment by nskw** [comment]
Thank you for your reply. 
Error text is below. 

Constrained Instances: '114', '154/38'
Constraint Name: UnknownConstraint_154_0
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '157', '154/38'
Constraint Name: UnknownConstraint_154_1
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '114', '164/38'
Constraint Name: UnknownConstraint_164_0
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '157', '164/38'
Constraint Name: UnknownConstraint_164_1
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '114', '175/38'
Constraint Name: UnknownConstraint_175_1
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '164/38', '175/38'
Constraint Name: UnknownConstraint_175_2
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '114', '178/38'
Constraint Name: UnknownConstraint_178_1
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '154/38', '178/38'
Constraint Name: UnknownConstraint_178_2
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '117', '197/38'
Constraint Name: UnknownConstraint_197_1
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------
Constrained Instances: '117', '200/38'
Constraint Name: UnknownConstraint_200_1
Error Details: Constraint is not supported. Unknown constraint has been exported.
---------------------------------------------------------------------------------

**Comment by nskw** [comment]
At present, the error message is disappeared after adding some constraints. 
Thank you!

**Comment by DanielePucci** [comment]
So, we close this issue.
