### ISSUE TITLE
How to debug URDF file

### ISSUE THREAD

**Issue by nskw** [robotology/simmechanics-to-urdf#12]
I want to know how to debug the URDF file. 
Are there any tools for debugging such as the visualization of the model?

**Comment by traversaro** [comment]
Hi @nskw , 
  for debugging the produced URDF I suggest that you use the `urdf_to_graphviz` command (you should have installed it if you have the `urdfdom` package installed. This command produces a PDF with a graph representation of joints and links of the model.

Other then that, you can try to load the URDF model in Gazebo: http://gazebosim.org/ . If you load it without any plugin it will collapse because no torques is actuated, but inserting it in a paused simulation you get a visualization of how the model is visualized. You can also visualize the COMs and inertia, for debugging even the inertia values.

**Comment by nskw** [comment]
Thank you!
I tried urdf_to_graphiz to the urdf file which is generated by xml file in test directory. 
Then, I got the following messages. 

Created file iCubHeidelberg01_SIM_MODEL.gv
sh: 1: dot: not found
Created file iCubHeidelberg01_SIM_MODEL.pdf

But, I got only gv file and could not find any pdf files. 
I installed liburdfdom-tools before I executed urdf_to_graphiz. 
Do I need other packages?

**Comment by traversaro** [comment]
Yes, the `urdf_to_graphviz` tool calls internall the `dot` program, that is contained in the `graphviz` package, that you can install as:
~~~
sudo apt-get install graphviz
~~~

**Comment by nskw** [comment]
I could produce PDF!
Thank you!

**Comment by iron76** [comment]
I think @nskw and @kzts need also some hints on how to load the URDF in gazebo. @traversaro can you give him some directions? As far as I know we should first obtain an SDF from the URDF (using `gz sdf -p MODEL.urdf`). Then the model can be included setting the variable GAZEBO_MODEL_PATH to the directory containing the SDF (using `export GAZEBO_MODEL_PATH =\parh\to\sdf\direcory` to be included in the .bashrc).  Will this be enough?

**Comment by traversaro** [comment]
To add a model in gazebo you need to create a new directory exclusively for that model.  

This directory can be created in `~/.gazebo/models` (where `~` stands for the user home directory in *nix systems) or in any directory that is then added to the `GAZEBO_MODEL_PATH` environmental variable.

Let's say for example that you want to keep your gazebo models in `~/gazebo-models`. 
First you add the directory to the `GAZEBO_MODEL_PATH` environmental variable (for example adding to the bashrc the line : 
~~~
export GAZEBO_MODEL_PATH=~/gazebo-models
~~~ 

Then you can create the robot directory in `~/gazebo-models` , for example `~/gazebo-models/athleteRobots`. In this directory you need to put the URDF model that you created, and also a file named  `model.config`, that contains all the informations that Gazebo needs to load the model. A template content for the `model.config` file is:
~~~
<?xml version="1.0"?>
<model>
  <name>My Robot</name>
  <version>1.0</version>
  <sdf>model.urdf</sdf>

  <author>
   <name>My Name</name>
   <email>me@my.email</email>
  </author>

  <description>
    My awesome robot.
  </description>
</model>
~~~

Note that the content of the `<sdf>` tag can be both a sdf file or even a urdf  file. In that case Gazebo will automatically convert the model while loading it. 

For more info, check : 
 * http://gazebosim.org/tutorials?tut=model_structure&cat=build_robot
 * http://gazebosim.org/tutorials/?tut=build_robot

**Comment by traversaro** [comment]
@iron76 Do you need also to simulate a YARP interface for the simulated robot in Gazebo? In that case I can review a bit the documentation of `gazebo-yarp-plugins` on how to add the plugins to an existing model.

**Comment by iron76** [comment]
Yes, this is the plan. At present we have two major activities on-going with @nskw and @kzts. The first one is to use the URDF for configuring the yarp-wholebodyinterface (https://github.com/robotology/yarp-wholebodyinterface). The second one is to use the URDF to simulate the athletebot in Gazebo using the `gazebo-yarp-plugins` (https://github.com/robotology/gazebo-yarp-plugins). Improvements on the documentation are definitively useful.

**Comment by kzts** [comment]
I want to confirm that we can make urdf files using `simmechanics-to-urdf` and we should prepare mesh files (dae files or stl files) for using robot models on gazebo. Because, urdf files don't  include mesh files in themselves.

**Comment by traversaro** [comment]
What do you mean by "urdf files don't include mesh files in themselves" ? Both simmechanics xml files and URDF file uses meshes that are contained in external `stl` or `dae` files. 
In particular Simmechanics Link should export the meshes of the model in `stl` format.

**Comment by kzts** [comment]
Thanks to you, I understood that `URDF` file uses meshes that are contained in external `stl` or` dae` files. Thank you.

**Comment by iron76** [comment]
@kzts, were you able to import the URDF in Gazebo?

**Comment by kzts** [comment]
Yes. We made simple figure pro-E files for viewing. We converted them to URDF. Gazebo veiwed our robot.

**Comment by iron76** [comment]
Can you share the URDF somewhere so that I can start some tests?

**Comment by kzts** [comment]
OK! I'll share it
