### ISSUE TITLE
Allow changing the robot name

### ISSUE THREAD

**Issue by diegoferigo** [robotology/simmechanics-to-urdf#24]
Referring to the attempt (https://github.com/robotology-playground/icub-model-generator/pull/49) of using in Gazebo the models generated directly from the CAD, there are issues in how the robot name is processed.

`icub-model-generator` uses the name from the CAD (e.g. `ICUB_2-5_BB_SIM_MODEL`), but `icub-gazebo-wholebody` (e.g. [`icub_fixed_no_hands`](https://github.com/robotology-playground/icub-gazebo-wholebody/blob/master/models/icub_fixed_no_hands/icub_fixed_no_hands.sdf#L11)) expects to get the robot as `iCub::`.

This mismatch generates the following error in Gazebo:
```
[Err] [Joint.cc:312] EXCEPTION: Couldn't Find Child Link[iCub::base_link]
[Err] [Model.cc:221] LoadJoint Failed
```
and the simulation doesn't work.

A possible workaround could be including an option to the configuration or the command line allowing to specify the name.

cc @traversaro @nunoguedelha @gabrielenava @S-Dafarra @DanielePucci 

See https://github.com/robotology/simmechanics-to-urdf/blob/master/simmechanics_to_urdf/firstgen.py#L459

**Comment by nunoguedelha** [comment]
Yes, actually, along with the changes on the small link inertias, the change setting the expected name `iCub` was done manually in this [fork of cub-models](https://github.com/nunoguedelha/icub-models/tree/feature/updateModels) for testing purposes, waiting for a proper implemented in the auto generation from CAD procedure. Refer to discussion (https://github.com/robotology-playground/icub-model-generator/pull/49#issuecomment-313058967).

If the iCub CAD name is relevant information to keep in the model, maybe we should rather change the mesh paths from `filename="package://iCub/meshes/...` to `filename="package://ICUB_2-5_BB_SIM_MODEL/meshes/...`, as well as `<yarpConfigurationFile>model://iCub/conf/...` to ` <yarpConfigurationFile>model://ICUB_2 5_BB_SIM_MODEL/conf/` and rename the folder in `icub-models` accordingly.

**Comment by traversaro** [comment]
Tipically we always remove CAD names and substitute them with more URDF-friendly names, as we cannot ensure stability of CAD naming schemes.

**Comment by nunoguedelha** [comment]
@diegoferigo I was wrong in my previous message!

While the path for the meshes and the configuration `.ini` files have to match the tags `<mesh filename=.../>` and `<yarpConfigurationFile>` definitions, there is no relation to the model name `<robot name="ICUB_2-5_BB_SIM_MODEL">`.
Instead, the robot name has to match the model links referenced in the model `sdf` file like  for instance `icub-gazebo-wholebody/models/icub_feet_fixed/icub_feet_fixed.sdf`:
```
<?xml version='1.0'?>
<sdf version='1.4'>
  <model name="iCub">
    <include>
      <uri>model://iCubGenova04</uri>
      <pose>0.0 0 0.63 0 0 3.14</pose>
    </include>

    <joint name="fixed right to ground" type="revolute">
      <parent>world</parent>
      <child>ICUB_2-5_BB_SIM_MODEL::r_foot</child>
      ...
    </joint>
    <joint name="fixed left to ground" type="revolute">
      <parent>world</parent>
      <child>ICUB_2-5_BB_SIM_MODEL::l_foot</child>
      ...
    </joint>

  </model>
</sdf>
```
as explained in https://github.com/robotology-playground/icub-models/pull/2#issuecomment-315349735.

@traversaro do you agree with this procedure, until we find a better global solution?

**Comment by nunoguedelha** [comment]
Sorry @traversaro I hadn't seen your response https://github.com/robotology/simmechanics-to-urdf/issues/24#issuecomment-315329973. So, still considering my last comment, we could for instance replace `ICUB_2-5_BB_SIM_MODEL` by `iCub2_5` and use it on the link references in the `sdf` file as described in the above comment.

**Comment by nunoguedelha** [comment]
So, there are 3 changes to implement:
[ ] update the python script `simmechanics_to_urdf/simmechanics_to_urdf/firstgen.py` that generates the URDF file, such that it sets the model name from a parameter defined in the YAML config file.
[ ] define in the YAML config file(s) the parameter in question (`robotName`). For instance:
```
robotName: iCub2_5
```
[ ] use that same parameter value in all the `conf/*.ini` files.

**Comment by traversaro** [comment]
For consistency with existing models I would go for `robotName: iCub`.

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/simmechanics-to-urdf/pull/26 .
